(cl:in-package pacmod_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          DRIVER_SEAT_OCCUPIED-VAL
          DRIVER_SEAT_OCCUPIED
          DRIVER_SEAT_OCCUPIED_IS_VALID-VAL
          DRIVER_SEAT_OCCUPIED_IS_VALID
          PASSENGER_SEAT_OCCUPIED-VAL
          PASSENGER_SEAT_OCCUPIED
          PASSENGER_SEAT_OCCUPIED_IS_VALID-VAL
          PASSENGER_SEAT_OCCUPIED_IS_VALID
          REAR_SEAT_OCCUPIED-VAL
          REAR_SEAT_OCCUPIED
          REAR_SEAT_OCCUPIED_IS_VALID-VAL
          REAR_SEAT_OCCUPIED_IS_VALID
          DRIVER_SEATBELT_BUCKLED-VAL
          DRIVER_SEATBELT_BUCKLED
          DRIVER_SEATBELT_BUCKLED_IS_VALID-VAL
          DRIVER_SEATBELT_BUCKLED_IS_VALID
          PASSENGER_SEATBELT_BUCKLED-VAL
          PASSENGER_SEATBELT_BUCKLED
          PASSENGER_SEATBELT_BUCKLED_IS_VALID-VAL
          PASSENGER_SEATBELT_BUCKLED_IS_VALID
          REAR_SEATBELT_BUCKLED-VAL
          REAR_SEATBELT_BUCKLED
          REAR_SEATBELT_BUCKLED_IS_VALID-VAL
          REAR_SEATBELT_BUCKLED_IS_VALID
))