(cl:in-package pacmod_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          HEADLIGHTS_ON-VAL
          HEADLIGHTS_ON
          HEADLIGHTS_ON_IS_VALID-VAL
          HEADLIGHTS_ON_IS_VALID
          HEADLIGHTS_ON_BRIGHT-VAL
          HEADLIGHTS_ON_BRIGHT
          HEADLIGHTS_ON_BRIGHT_IS_VALID-VAL
          HEADLIGHTS_ON_BRIGHT_IS_VALID
          FOG_LIGHTS_ON-VAL
          FOG_LIGHTS_ON
          FOG_LIGHTS_ON_IS_VALID-VAL
          FOG_LIGHTS_ON_IS_VALID
          HEADLIGHTS_MODE-VAL
          HEADLIGHTS_MODE
          HEADLIGHTS_MODE_IS_VALID-VAL
          HEADLIGHTS_MODE_IS_VALID
))