(cl:in-package pacmod_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          FRONT_WIPING-VAL
          FRONT_WIPING
          FRONT_WIPING_IS_VALID-VAL
          FRONT_WIPING_IS_VALID
          FRONT_SPRAYING-VAL
          FRONT_SPRAYING
          FRONT_SPRAYING_IS_VALID-VAL
          FRONT_SPRAYING_IS_VALID
          REAR_WIPING-VAL
          REAR_WIPING
          REAR_WIPING_IS_VALID-VAL
          REAR_WIPING_IS_VALID
          REAR_SPRAYING-VAL
          REAR_SPRAYING
          REAR_SPRAYING_IS_VALID-VAL
          REAR_SPRAYING_IS_VALID
          SPRAY_NEAR_EMPTY-VAL
          SPRAY_NEAR_EMPTY
          SPRAY_NEAR_EMPTY_IS_VALID-VAL
          SPRAY_NEAR_EMPTY_IS_VALID
          SPRAY_EMPTY-VAL
          SPRAY_EMPTY
          SPRAY_EMPTY_IS_VALID-VAL
          SPRAY_EMPTY_IS_VALID
))