// Generated by gencpp from file pacmod_msgs/KeyValuePair.msg
// DO NOT EDIT!


#ifndef PACMOD_MSGS_MESSAGE_KEYVALUEPAIR_H
#define PACMOD_MSGS_MESSAGE_KEYVALUEPAIR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pacmod_msgs
{
template <class ContainerAllocator>
struct KeyValuePair_
{
  typedef KeyValuePair_<ContainerAllocator> Type;

  KeyValuePair_()
    : key()
    , value()  {
    }
  KeyValuePair_(const ContainerAllocator& _alloc)
    : key(_alloc)
    , value(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _key_type;
  _key_type key;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::pacmod_msgs::KeyValuePair_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pacmod_msgs::KeyValuePair_<ContainerAllocator> const> ConstPtr;

}; // struct KeyValuePair_

typedef ::pacmod_msgs::KeyValuePair_<std::allocator<void> > KeyValuePair;

typedef boost::shared_ptr< ::pacmod_msgs::KeyValuePair > KeyValuePairPtr;
typedef boost::shared_ptr< ::pacmod_msgs::KeyValuePair const> KeyValuePairConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pacmod_msgs::KeyValuePair_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pacmod_msgs::KeyValuePair_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pacmod_msgs::KeyValuePair_<ContainerAllocator1> & lhs, const ::pacmod_msgs::KeyValuePair_<ContainerAllocator2> & rhs)
{
  return lhs.key == rhs.key &&
    lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pacmod_msgs::KeyValuePair_<ContainerAllocator1> & lhs, const ::pacmod_msgs::KeyValuePair_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pacmod_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pacmod_msgs::KeyValuePair_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pacmod_msgs::KeyValuePair_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pacmod_msgs::KeyValuePair_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pacmod_msgs::KeyValuePair_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pacmod_msgs::KeyValuePair_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pacmod_msgs::KeyValuePair_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pacmod_msgs::KeyValuePair_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cf57fdc6617a881a88c16e768132149c";
  }

  static const char* value(const ::pacmod_msgs::KeyValuePair_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcf57fdc6617a881aULL;
  static const uint64_t static_value2 = 0x88c16e768132149cULL;
};

template<class ContainerAllocator>
struct DataType< ::pacmod_msgs::KeyValuePair_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pacmod_msgs/KeyValuePair";
  }

  static const char* value(const ::pacmod_msgs::KeyValuePair_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pacmod_msgs::KeyValuePair_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string key\n"
"string value\n"
;
  }

  static const char* value(const ::pacmod_msgs::KeyValuePair_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pacmod_msgs::KeyValuePair_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.key);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct KeyValuePair_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pacmod_msgs::KeyValuePair_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pacmod_msgs::KeyValuePair_<ContainerAllocator>& v)
  {
    s << indent << "key: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.key);
    s << indent << "value: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PACMOD_MSGS_MESSAGE_KEYVALUEPAIR_H
