# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from pacmod_msgs/ComponentRpt.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class ComponentRpt(genpy.Message):
  _md5sum = "1d5b5cb01195437dc5e2f534206c1017"
  _type = "pacmod_msgs/ComponentRpt"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header

uint8 component_type
uint8 component_func
uint8 counter
uint8 complement

bool config_fault

uint8 COMPONENT_TYPE_PACMOD = 0
uint8 COMPONENT_TYPE_PACMINI = 1
uint8 COMPONENT_TYPE_PACMICRO = 2

uint8 COMPONENT_FUNC_PACMOD = 0
uint8 COMPONENT_FUNC_STEERING_AND_STEERING_COLUMN = 1
uint8 COMPONENT_FUNC_ACCELERATOR_AND_BRAKING = 2
uint8 COMPONENT_FUNC_BRAKING = 3
uint8 COMPONENT_FUNC_SHIFTING = 4
uint8 COMPONENT_FUNC_STEERING = 5
uint8 COMPONENT_FUNC_E_SHIFTER = 6
uint8 COMPONENT_FUNC_WATCHDOG = 7

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  # Pseudo-constants
  COMPONENT_TYPE_PACMOD = 0
  COMPONENT_TYPE_PACMINI = 1
  COMPONENT_TYPE_PACMICRO = 2
  COMPONENT_FUNC_PACMOD = 0
  COMPONENT_FUNC_STEERING_AND_STEERING_COLUMN = 1
  COMPONENT_FUNC_ACCELERATOR_AND_BRAKING = 2
  COMPONENT_FUNC_BRAKING = 3
  COMPONENT_FUNC_SHIFTING = 4
  COMPONENT_FUNC_STEERING = 5
  COMPONENT_FUNC_E_SHIFTER = 6
  COMPONENT_FUNC_WATCHDOG = 7

  __slots__ = ['header','component_type','component_func','counter','complement','config_fault']
  _slot_types = ['std_msgs/Header','uint8','uint8','uint8','uint8','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,component_type,component_func,counter,complement,config_fault

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ComponentRpt, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.component_type is None:
        self.component_type = 0
      if self.component_func is None:
        self.component_func = 0
      if self.counter is None:
        self.counter = 0
      if self.complement is None:
        self.complement = 0
      if self.config_fault is None:
        self.config_fault = False
    else:
      self.header = std_msgs.msg.Header()
      self.component_type = 0
      self.component_func = 0
      self.counter = 0
      self.complement = 0
      self.config_fault = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_5B().pack(_x.component_type, _x.component_func, _x.counter, _x.complement, _x.config_fault))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.component_type, _x.component_func, _x.counter, _x.complement, _x.config_fault,) = _get_struct_5B().unpack(str[start:end])
      self.config_fault = bool(self.config_fault)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_5B().pack(_x.component_type, _x.component_func, _x.counter, _x.complement, _x.config_fault))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.component_type, _x.component_func, _x.counter, _x.complement, _x.config_fault,) = _get_struct_5B().unpack(str[start:end])
      self.config_fault = bool(self.config_fault)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_5B = None
def _get_struct_5B():
    global _struct_5B
    if _struct_5B is None:
        _struct_5B = struct.Struct("<5B")
    return _struct_5B
