# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from pacmod_msgs/DoorRpt.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class DoorRpt(genpy.Message):
  _md5sum = "a2ffa235d04f8d5d5e349a5d9caead12"
  _type = "pacmod_msgs/DoorRpt"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header

bool driver_door_open
bool driver_door_open_is_valid
bool passenger_door_open
bool passenger_door_open_is_valid
bool rear_driver_door_open
bool rear_driver_door_open_is_valid
bool rear_passenger_door_open
bool rear_passenger_door_open_is_valid
bool hood_open
bool hood_open_is_valid
bool trunk_open
bool trunk_open_is_valid
bool fuel_door_open
bool fuel_door_open_is_valid

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','driver_door_open','driver_door_open_is_valid','passenger_door_open','passenger_door_open_is_valid','rear_driver_door_open','rear_driver_door_open_is_valid','rear_passenger_door_open','rear_passenger_door_open_is_valid','hood_open','hood_open_is_valid','trunk_open','trunk_open_is_valid','fuel_door_open','fuel_door_open_is_valid']
  _slot_types = ['std_msgs/Header','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,driver_door_open,driver_door_open_is_valid,passenger_door_open,passenger_door_open_is_valid,rear_driver_door_open,rear_driver_door_open_is_valid,rear_passenger_door_open,rear_passenger_door_open_is_valid,hood_open,hood_open_is_valid,trunk_open,trunk_open_is_valid,fuel_door_open,fuel_door_open_is_valid

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(DoorRpt, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.driver_door_open is None:
        self.driver_door_open = False
      if self.driver_door_open_is_valid is None:
        self.driver_door_open_is_valid = False
      if self.passenger_door_open is None:
        self.passenger_door_open = False
      if self.passenger_door_open_is_valid is None:
        self.passenger_door_open_is_valid = False
      if self.rear_driver_door_open is None:
        self.rear_driver_door_open = False
      if self.rear_driver_door_open_is_valid is None:
        self.rear_driver_door_open_is_valid = False
      if self.rear_passenger_door_open is None:
        self.rear_passenger_door_open = False
      if self.rear_passenger_door_open_is_valid is None:
        self.rear_passenger_door_open_is_valid = False
      if self.hood_open is None:
        self.hood_open = False
      if self.hood_open_is_valid is None:
        self.hood_open_is_valid = False
      if self.trunk_open is None:
        self.trunk_open = False
      if self.trunk_open_is_valid is None:
        self.trunk_open_is_valid = False
      if self.fuel_door_open is None:
        self.fuel_door_open = False
      if self.fuel_door_open_is_valid is None:
        self.fuel_door_open_is_valid = False
    else:
      self.header = std_msgs.msg.Header()
      self.driver_door_open = False
      self.driver_door_open_is_valid = False
      self.passenger_door_open = False
      self.passenger_door_open_is_valid = False
      self.rear_driver_door_open = False
      self.rear_driver_door_open_is_valid = False
      self.rear_passenger_door_open = False
      self.rear_passenger_door_open_is_valid = False
      self.hood_open = False
      self.hood_open_is_valid = False
      self.trunk_open = False
      self.trunk_open_is_valid = False
      self.fuel_door_open = False
      self.fuel_door_open_is_valid = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_14B().pack(_x.driver_door_open, _x.driver_door_open_is_valid, _x.passenger_door_open, _x.passenger_door_open_is_valid, _x.rear_driver_door_open, _x.rear_driver_door_open_is_valid, _x.rear_passenger_door_open, _x.rear_passenger_door_open_is_valid, _x.hood_open, _x.hood_open_is_valid, _x.trunk_open, _x.trunk_open_is_valid, _x.fuel_door_open, _x.fuel_door_open_is_valid))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 14
      (_x.driver_door_open, _x.driver_door_open_is_valid, _x.passenger_door_open, _x.passenger_door_open_is_valid, _x.rear_driver_door_open, _x.rear_driver_door_open_is_valid, _x.rear_passenger_door_open, _x.rear_passenger_door_open_is_valid, _x.hood_open, _x.hood_open_is_valid, _x.trunk_open, _x.trunk_open_is_valid, _x.fuel_door_open, _x.fuel_door_open_is_valid,) = _get_struct_14B().unpack(str[start:end])
      self.driver_door_open = bool(self.driver_door_open)
      self.driver_door_open_is_valid = bool(self.driver_door_open_is_valid)
      self.passenger_door_open = bool(self.passenger_door_open)
      self.passenger_door_open_is_valid = bool(self.passenger_door_open_is_valid)
      self.rear_driver_door_open = bool(self.rear_driver_door_open)
      self.rear_driver_door_open_is_valid = bool(self.rear_driver_door_open_is_valid)
      self.rear_passenger_door_open = bool(self.rear_passenger_door_open)
      self.rear_passenger_door_open_is_valid = bool(self.rear_passenger_door_open_is_valid)
      self.hood_open = bool(self.hood_open)
      self.hood_open_is_valid = bool(self.hood_open_is_valid)
      self.trunk_open = bool(self.trunk_open)
      self.trunk_open_is_valid = bool(self.trunk_open_is_valid)
      self.fuel_door_open = bool(self.fuel_door_open)
      self.fuel_door_open_is_valid = bool(self.fuel_door_open_is_valid)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_14B().pack(_x.driver_door_open, _x.driver_door_open_is_valid, _x.passenger_door_open, _x.passenger_door_open_is_valid, _x.rear_driver_door_open, _x.rear_driver_door_open_is_valid, _x.rear_passenger_door_open, _x.rear_passenger_door_open_is_valid, _x.hood_open, _x.hood_open_is_valid, _x.trunk_open, _x.trunk_open_is_valid, _x.fuel_door_open, _x.fuel_door_open_is_valid))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 14
      (_x.driver_door_open, _x.driver_door_open_is_valid, _x.passenger_door_open, _x.passenger_door_open_is_valid, _x.rear_driver_door_open, _x.rear_driver_door_open_is_valid, _x.rear_passenger_door_open, _x.rear_passenger_door_open_is_valid, _x.hood_open, _x.hood_open_is_valid, _x.trunk_open, _x.trunk_open_is_valid, _x.fuel_door_open, _x.fuel_door_open_is_valid,) = _get_struct_14B().unpack(str[start:end])
      self.driver_door_open = bool(self.driver_door_open)
      self.driver_door_open_is_valid = bool(self.driver_door_open_is_valid)
      self.passenger_door_open = bool(self.passenger_door_open)
      self.passenger_door_open_is_valid = bool(self.passenger_door_open_is_valid)
      self.rear_driver_door_open = bool(self.rear_driver_door_open)
      self.rear_driver_door_open_is_valid = bool(self.rear_driver_door_open_is_valid)
      self.rear_passenger_door_open = bool(self.rear_passenger_door_open)
      self.rear_passenger_door_open_is_valid = bool(self.rear_passenger_door_open_is_valid)
      self.hood_open = bool(self.hood_open)
      self.hood_open_is_valid = bool(self.hood_open_is_valid)
      self.trunk_open = bool(self.trunk_open)
      self.trunk_open_is_valid = bool(self.trunk_open_is_valid)
      self.fuel_door_open = bool(self.fuel_door_open)
      self.fuel_door_open_is_valid = bool(self.fuel_door_open_is_valid)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_14B = None
def _get_struct_14B():
    global _struct_14B
    if _struct_14B is None:
        _struct_14B = struct.Struct("<14B")
    return _struct_14B
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
